name: Merge & Deploy Release branch

on:
  workflow_dispatch:
    branches:
      - "**"
  push:
    branches:
      - release

jobs:
  dev-deployment:
    name: Development
    runs-on: ubuntu-latest
    environment: "DEVELOPMENT"
    env:
      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      API_KEY: ${{secrets.API_KEY}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Install UI dependencies
        run: yarn install --frozen-lockfile

      - name: Unit tests
        run: yarn test:unit --ci

      - name: Build UI package
        run: |
          sed -i -e 's/xxxx/${{ env.API_KEY }}/g' ./.env.dev
          yarn build:dev

      - name: CDK Bootstrap
        run: yarn bootstrap

      - name: CDK Deployment
        run: yarn deploy -c env=dev --require-approval never

      - name: Functional test
        run: echo 'Functional test'
